CoulterDaq:
  enable: true
  RunControl:
    enable: true
    runState: Stopped
    runRate: 1 Hz
  dataWriter:
    enable: true
    dataFile: ''
    open: false
    bufferSize: 0
    maxFileSize: 0
  Coulter[*]:
    enable: true
    TestRam:
      0: >-
        0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
        25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,
        47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,
        69,70,71,72,73,74,75,76,77,78,79,80,81
      500: >-
        3,5,3,52,5,67,7,67
    Xadc:
      enable: true
      OT Limit: '-273.1'
    AxiVersion:
      enable: true
      ScratchPad: 0
      FpgaReloadHalt: 0
      FpgaReloadAddress: 0
    AcquisitionControl:
      enable: true
      ScDelay: 25088
      ScPosWidth: 4096
      ScNegWidth: 4096
      ScCount: 256
      MckDelay: 128
      MckPosWidth: 9
      MckNegWidth: 9
      MckCount: 16
      AdcClkDelay: 0
      AdcClkPosWidth: 4
      AdcClkNegWidth: 4
      AdcWindowDelay: 210
      MckDisable: false
      ClkDisable: false
      InvertMck: false
    ASIC[*]:
      enable: false
      EnaAnalogMonitor: false
      pbitt: 1
      cs: 0
      atest: 0
      vdacm: 0
      hrtest: 0
      sbm: 1
      sb: 1
      test: 0
      saux: 1
      slrb: 1
      claen: 0
      pb: 511
      tr: 0
      sse: 0
      disen: 0
      pa: 250
      esm: 0
      t: 7
      dd: 1
      sabtest: 0
      clab: 1
      tres: 0
      somi: 0
      sm[31:0]: 0
      sm[63:32]: 0
      sm[95:64]: 0
      st[31:0]: 0
      st[63:32]: 0
      st[95:64]: 0
    AdcConfig:
      enable: false
      Pdwn: false
      BankConfig[*]:
        enable: false
        ExternalPdwnMode: Full Power Down
        InternalPdwnMode: Chip Run
        DutyCycleStabilizer: 'On'
        ClockDivide: Divide by 1
        ChopMode: 'Off'
        DevIndexMask: 0b1111111
        DevIndexMask[DCO:FCO]: 0b11
        UserTestModeCfg: single
        OutputTestMode: 'Off'
        OffsetAdjust: 0
        OutputInvert: false
        OutputFormat: Twos Compliment
    AdcReadoutBank[*]:
      enable: true
      ChannelDelay[0]: 0
      ChannelDelay[1]: 0
      ChannelDelay[2]: 0
      ChannelDelay[3]: 0
      ChannelDelay[4]: 0
      ChannelDelay[5]: 0
      FrameDelay: 0
    CoulterPgp:
      enable: true
      Pgp2bAxi:
        enable: true
        Loopback: 'Off'
        LocData: 0
        LocDataEn: false
        AutoStatus: false
